/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Chai {
  export type MemoStruct = {
    message: string;
    name: string;
    timestamp: BigNumberish;
    amount: BigNumberish;
    from: AddressLike;
  };

  export type MemoStructOutput = [
    message: string,
    name: string,
    timestamp: bigint,
    amount: bigint,
    from: string
  ] & {
    message: string;
    name: string;
    timestamp: bigint;
    amount: bigint;
    from: string;
  };
}

export interface ChaiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyChai"
      | "getChaiDonationAmount"
      | "getMemos"
      | "owner"
      | "totalDonations"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewMemo"): EventFragment;

  encodeFunctionData(
    functionFragment: "buyChai",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChaiDonationAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getMemos", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalDonations",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyChai", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChaiDonationAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMemos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDonations",
    data: BytesLike
  ): Result;
}

export namespace NewMemoEvent {
  export type InputTuple = [
    message: string,
    name: string,
    timestamp: BigNumberish,
    amount: BigNumberish,
    from: AddressLike
  ];
  export type OutputTuple = [
    message: string,
    name: string,
    timestamp: bigint,
    amount: bigint,
    from: string
  ];
  export interface OutputObject {
    message: string;
    name: string;
    timestamp: bigint;
    amount: bigint;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Chai extends BaseContract {
  connect(runner?: ContractRunner | null): Chai;
  waitForDeployment(): Promise<this>;

  interface: ChaiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyChai: TypedContractMethod<
    [_name: string, _message: string],
    [void],
    "payable"
  >;

  getChaiDonationAmount: TypedContractMethod<[], [bigint], "view">;

  getMemos: TypedContractMethod<[], [Chai.MemoStructOutput[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  totalDonations: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyChai"
  ): TypedContractMethod<[_name: string, _message: string], [void], "payable">;
  getFunction(
    nameOrSignature: "getChaiDonationAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMemos"
  ): TypedContractMethod<[], [Chai.MemoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalDonations"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "NewMemo"
  ): TypedContractEvent<
    NewMemoEvent.InputTuple,
    NewMemoEvent.OutputTuple,
    NewMemoEvent.OutputObject
  >;

  filters: {
    "NewMemo(string,string,uint256,uint256,address)": TypedContractEvent<
      NewMemoEvent.InputTuple,
      NewMemoEvent.OutputTuple,
      NewMemoEvent.OutputObject
    >;
    NewMemo: TypedContractEvent<
      NewMemoEvent.InputTuple,
      NewMemoEvent.OutputTuple,
      NewMemoEvent.OutputObject
    >;
  };
}
